### ISSUE TITLE
Stephanie - August 2019

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#115]
**Fieldwork**

- [x] Absolutely need two rounds of CO2 and CH4 measurements, hopefully weeks 2 and 4; ideally with Norbert trailing Gru; but perhaps Norbert only, because...
- [x] Test Gru, work with Licor, send back if necessary; I'm increasingly thinking the fall 2019 transplant paper is not possible
- [ ] We want to fill in all missing inventory species before fall
- [ ] Survey and inventory a shore plot for Nate, with BBL
- [ ] Repaint plot stakes
- [x] Relabel litter traps
- [x] Reflag trail to North Branch
- [ ] Do we want to rebuild LSLE-C trap, or drop?
- [x] Litter collection last week of August

**Lab**
- [x] We can't get too far behind on litter data, particularly with fall coming; actively schedule a litter sorting day. Note Kalyn and Abigail both have 20 hours set aside rest of FY to help with this and other things, if they have time
- [x] See https://github.com/PNNL-PREMIS/PREMIS-ghg/issues/111#issuecomment-509019751
- [ ] Think about #112 and let's ask about access to a Wiley mill or ?

**Coding/data**
- [x] Data pipeline improvements listed in #110 and #106
- [x] Script to handle and visualize litter data
- [ ] Js numbers for Nate 

**Manuscripts and analyses**
- [x] Your [manuscript's discussion](https://github.com/PNNL-PREMIS/PREMIS-ghg/issues/111#issuecomment-509019751) closes August 22; be prepared for editor decision and to move quickly in the following weeks. Interestingly it looks like there are only two reviewers, not three, so we probably won't get any more comments!
- [ ] Are there any missing proximity measurements that still need to be done?!?
- [x] Background reading for AGU/combo paper - list [here](https://github.com/PNNL-PREMIS/PREMIS-ghg/issues/93#issuecomment-508899674), 1/week? We want to actively start to design analysis in September
- [x] Help as needed with B's temporal paper revision

**Mentoring**
- [x] With BBL, be available for Lillie as needed; provide feedback as her manuscript outline develops; help with R coding
- [x] Meet and be available for new high school students - Jason and Darlin
 
Obviously this doesn't include any measurements or data coordination for storm surge experiment. _Please_  talk with B if workload is getting too heavy.

**Comment by stephpenn1** [comment]
**Stormsurge/other tasks**
- [ ] develop data pipeline for when dataloggers get put on network
- [ ] think of structure for logger/sensor naming in SS plots, work w Roy on this
- [ ] work w/ Roy to develop programs for new sapflow
- [ ] get new sapflow system up and running
- [ ] replace old sapflow wiring
- [ ] replace bad sensors
- [ ] order electrical items & mounting kits for sapflow dataloggers
- [ ] coral work - look up degree heating weeks calculation and possible model integration
- [ ] coordinate possible UMBS trip with Kayla - looks like it'd be ~ November
- [ ] organize 1207 w @lilliehaddock
