### ISSUE TITLE
May 2020 Checklist - SP

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#160]
**Transplant**
- [ ] Gru files
- [ ] is `drake` / read me up to date?

**TEMPEST**
- [ ] access sapflow dropbox w SERC email
- [ ] check data + do maintenance on wonky sensors
- [ ] ????

**COSORE**
- [ ] standards research: make edits on draft
- [ ] send survey out to AmeriFlux small group

**Comment by stephpenn1** [comment]
Meeting 5/15:
- field work
- end of transplant exp. next steps
- essd figs
- cosore: roadmap? 
- forte

**Comment by stephpenn1** [comment]
```
obs_count_data <- tibble()

log_obs <- function(d, step_name) {
  d %>% group_by(port) %>% summarise(n = n()) %>% mutate(step = step_name) %>% bind_rows(obs_count_data) ->> obs_count_data
}

sp_data %>%
  do_something %T>%
  log_obs("step 1") %>%
  something_else() %T>%
  log_obs("step 2") ...
```
