### ISSUE TITLE
Ben - April/May todo

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#18]
- [x] Finish North Branch plot layout
- [x] North branch inventory
- [x] GPS plots and send info to Jess
