### ISSUE TITLE
Stephanie - late August through September

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#50]
**Fieldwork**
- [x] Flux measurements every 7-10 days; skip 'extra' controls every other time. Work with Emily to coordinate Norbert use.
- [x] Continue regular well, weather station, and sapflow downloads.
- [x] Maintenance on sapflow batteries [link here](https://github.com/PNNL-PREMIS/PREMIS-sapflow/issues/2)
- [x] eoSense loaners–read manual, work with B to configure, install for ~5 weeks.
- [ ] Record tree-distance-to-collar data, following [existing data format](https://github.com/PNNL-PREMIS/PREMIS-ghg/blob/master/inventory_data/collar_proximity.csv) for #14 
- [x] Build (w/ Ben) 1-2 litter traps to test design. Modify plans as necessary; order materials for 100 traps.
- [x] Build and install 100 traps (~~second~~ first half of September); see #1 
- [x] Tree inventory: finish species ID started in spring.
- [ ] We probably need to do a little maintenance on Norbert–at the very least, 'zero' his IRGA. Talk to Pat about how they do this and whether we can use. (Hopefully tank of CO2 + scrub + desiccant setup.)
- [x] Finish Stuart test; look at data (including from rainstorm right now 8/21 2 PM); move to SALT plot, and install with eight chambers.

**Coding and office**
- [x] Weather station QC script. Should visualize data, report s.d. between temperature (for each depth) and moisture probes (up and down), etc. It should read in all available weather data from folder; eliminate any duplicate observations if necessary; produce diagnostics following licorplot model; and write out an output dataset.
- [x] Modify `licordat.R` to handle read in continuous (i.e. Stuart) Licor data.
- [ ] Database. Let's schedule a couple hours in September. New student Rebecca will be starting and would be good to have you ready for that.
- [ ] Let's talk with Pat about installing boardwalk (to cross the muddy crick by parking lot) at GCREW.

**Writing**
- [x] Let's sit down and outline–very tentatively–the proximity analysis paper.
- [x] At least one hour per week on background reading in preparation for proximity analysis. Add any notes to the Google Doc.
- [x] This is useful; please read. http://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1005619&type=printable

Hi @stephpenn1 how's this look?

**Comment by bpbond** [comment]
Note there's at least two sections of discarded boardwalk down in North Branch. We might be able to re-purpose for GCREW.
