### ISSUE TITLE
Winter 18-19 Field Checklist

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-ghg#58]
- [x] Winterize sapflow (this should be done before/beginning of winter)
- [x] Install boardwalk at HSLE
- [ ] Finish dist-to-tree recording
- [x] Build better infrastructure for sapflow batteries
- [x] Raise main wires from ground
- [x] Tree [inventory](https://github.com/PNNL-PREMIS/PREMIS-seawater/issues/1) in James' plots

**Comment by bpbond** [comment]
Email from Nick on December 10, 2018:
```
By the way, we shipped all of our gear out tonight.

I left a yellow bucket in the green shed with the extra vials/syringes
for tree sampling, your zip ties, and pipe cutter. We used all your
extra well stuff.

I deployed a water level logger in your GCrEW shoreline well, sampled
it for pH, O2, salinity, CO2, CH4, 13CH4, and N2O. Noticed a hydrogen
sulfide smell which is also a useful data point. I then pumped it dry
(it fills back up in about an hour typically), which got rid of a lot
of black stuff. When you redeploy the salinity probe you can just keep
it on its own string—my probe should be near the bottom.

Didn’t have time to do anything at canoe shed or north branch, but I
would suggest pumping out the wells at some point perhaps before
redeploying salinity probes to clean them up. Pat should have a pump
and I told him that a few of our new wells could use more pumping
too—some have a thick sludge in them from installation. Eventually
I’ll want to do semi frequent water samplings from all the wells so we
could also think about purchasing another field peristaltic pump (I
need mine for Beaver Creek fairly frequently).
```

**Comment by bpbond** [comment]
- [ ] Move all our PVC on the ground onto the GCREW "spare PVC" racks

**Comment by stephpenn1** [comment]
- [ ] 1x/month download James’ sensor data, send to Aditi, upload on github
- [ ] take GHG tree samples (will add protocol link here later)
- [ ] purge MSLE and LSLE wells
- [ ] re-launch conductivity sensors in wells
- [ ] take tree cores from the 6 shoreline maples (tentative)

**Comment by stephpenn1** [comment]
- [ ] fix 3 cut sensors at LSLE weather station
- [ ] check left air pump inside Stuart - looks like it’s possibly cracked

**Comment by bpbond** [comment]
- [ ] Put Stuart chamber/tree pairings into repo
- [ ] Enter temperatures measured while Norbert had broken thermometer; this will need a custom code adjustment too
- [ ] January: pack and ship Norbert back to Licor for (i) fixing temperature sensor and (ii) recalibration? Will need an RMA obviously and to confirm that it'll take weeks not months
- [ ] Plan litterpalooza

**Comment by bpbond** [comment]
Brought over from #68 :

- [ ] Tighten guy wires on met station towers and re-plumb as necessary
- [ ] Re-mark all transplant flags
- [ ] Order new sensors for poor Canoe Shed station and replace, protecting them!
