### ISSUE TITLE
Stephanie - February

### ISSUE THREAD

**Issue by bpbond** [PNNL-PREMIS/PREMIS-ghg#81]
### Overview

**Field**

- [ ] Stuart seasonal maintenance
- [x] Download sensors
- [x] Email Nate + Charlotte about when to start up sapflow again
- [x] Check weather stations - replace batteries, inventory broken sensors, download
- [x] Order new sensors for MSLE wx station 
- [ ] Winter maintenance; see #58 
- [x] B and S to tag and DBH saltwater addition plots ~~- need to order tree tags and ss nails~~
- [ ] Check Port 8 temperature sensor input (issue #82)

**Manuscript**

- [x] Enter data from last Friday at North Branch
- [ ] Finish proximity measurements: ~~2 collars at Canoe Shed,~~ rest of North Branch
- [x] Introduction and results full text (not outline) form and close to done
- [x] Close to final figures
- [x] Add to discussion outline points as they come up
- [x] Add figure captions
- [ ] Circulate mostly complete version (except discussion) to J,N,P by February 22

### Week 3

- [x] Introduction and results full text (not outline) form and close to done
- [x] Update HIII moisture boundaries 
- [ ] Produce tables for model outputs in RMarkdown
- [x] Add BA% to table
- [x] Change facet labels to site names instead of salinity
- [x] Fix zeros on cumulative BA figure 
- [x] Add result bullet points
- [ ] Stuart seasonal maintenance 
- [ ] Circulate mostly complete version (except discussion) to J,N,P by February 22

### Week 4

- [ ] Check Port 8 temperature sensor input (issue #82)
- [ ] Confirm broken sensor quantity/types, order new sensors for MSLE wx station
- [x] Get stuart running again

**Comment by bpbond** [comment]
Migrated open issues to #88
